export const ADD_CARRINHO = "ADD_CARRINHO";
export const REMOVE_CARRINHO = 'REMOVE_CARRINHO';
export const AUMENTAR_QTDE_CARRINHO = 'AUMENTAR_QTDE_CARRINHO';
export const DIMINUIR_QTDE_CARRINHO = 'DIMINUIR_QTDE_CARRINHO';
